### ISSUE TITLE
eigen3 is a dependency

### ISSUE THREAD

**Issue by ChuckM** [icebreaker-fpga/icebreaker-workshop#2]
Change the apt install line on the docs t include libeigen3-dev as a package.

**Comment by esden** [comment]
The workshops now use statically compiled binary only toolchain from [fomu](https://github.com/im-tomu/fomu-toolchain). As backup we refer to the main [summon-fpga-tools](https://github.com/esden/summon-fpga-tools) repository and there we are listing eigen as a dependency. This should close this issue, if not please feel free to reopen it. :)
