### ISSUE TITLE
Are there videos for the workshops?

### ISSUE THREAD

**Issue by fancellu** [icebreaker-fpga/icebreaker-workshop#8]
I ask as its not clear. I can't find any

Thanks

**Comment by esden** [comment]
Hi @fancellu,

No there are no videos associated with the workshop. The workshop is fully self directed. All you need to do is follow the instructions in the guide PDF, and there should be no need for further video explanations.

If you get stuck join our [Discord icebreaker channel](https://1bitsquared.com/pages/chat) and feel free to ask for support.

Good luck working through the workshop! :D

Cheers,
Piotr

**Comment by fancellu** [comment]
Ok thanks. Was just wondering if I'd missed something. 

I wanted to get some of the PMods but couldn't buy from the European store, to UK, as you know. 

And Mouser charges ridiculous shipping. Pity

**Comment by esden** [comment]
The Mouser shipping cost contains VAT and other fees that are required by the UK. We will have to implement the same thing in the German store too.

UK now requires complete pre-payment of VAT and customs by the store. So you have to pay that as part of the shipping cost.

Hope this helps. :)

**Comment by fancellu** [comment]
Have just got 3 pmods from mouser, all I had to do is also order a Fomu, and I got free shipping. 

So the answer seems to be to order enough things in one go

**Comment by esden** [comment]
I am glad it worked out. If you have any more questions I recommend that you use [Discord](https://1bitsquared.com/pages/chat) or our [Forum](https://forum.1bitsquared.com) in the future. GitHub issues are not really meant for Q&A like this. :)

Again, I am happy to hear that your issue was resolved. I hope you have fun with the hardware. :)
